file:
  upload:
    path: H:\EdgeDownLoad\GoCode_1\src\main\resources\images\   #文件上传目标路径
    allowTypes:             #文件上传允许的类型
      - image/jpeg
      - image/png
      - image/jpg
      - image/bmp
      - txt
      - xlsx
      - xls
